test('Hello world!', () => {

})

test('fail', () => {
    throw new error('Failure!')
})